### ISSUE TITLE
打denug包就行，打release包就报错  java.util.NoSuchElementException

### ISSUE THREAD

**Issue by SamSongShan** [FlyJingFish/AndroidAOP#19]
### 描述一下大概怎么回事
例如使用什么功能时会这样
打denug包就行，打release包就报错

### 你的代码
把你的出现错误的代码关键部分贴出来
androidAop.debugMode = true
androidAop.debugMode.variantOnlyDebug = true
androidAop.reflectInvokeMethod = false
androidAop.reflectInvokeMethod.variantOnlyDebug = false
# 0 mavenLocal 1 SonatypeCache 2 mavenCentral

# KSP Incremental processing
# https://kotlinlang.org/docs/ksp-incremental.html#program-elements
ksp.incremental.log=true
# track classpath
ksp.incremental.intermodule=true
### 错误日志
把错误日志贴出来

 Process: com.example.kotlinplus, PID: 8065
 java.lang.RuntimeException: Unable to create application com.example.kotlinplus.App: java.util.NoSuchElementException
 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5428)
 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
 	at android.os.Handler.dispatchMessage(Handler.java:103)
 	at android.os.Looper.loop(Looper.java:154)
 	at android.app.ActivityThread.main(ActivityThread.java:6141)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
 Caused by: java.util.NoSuchElementException
 	at java.util.ArrayList$Itr.next(ArrayList.java:834)
 	at com.flyjingfish.android_aop_annotation.AndroidAopJoinPoint.joinPointExecute(AndroidAopJoinPoint.java:106)
 	at com.flyjingfish.test_lib.collect.InitCollect2.init(InitCollect2.java)
 	at com.example.kotlinplus.App.onCreate(Unknown Source)
 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5425)
 	at android.app.ActivityThread.-wrap2(ActivityThread.java) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551) 
 	at android.os.Handler.dispatchMessage(Handler.java:103) 
 	at android.os.Looper.loop(Looper.java:154) 
 	at android.app.ActivityThread.main(ActivityThread.java:6141) 

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 

### 库的版本号:
说明库版本号
库版本：1.9.2

**Comment by FlyJingFish** [comment]
你导全了所有相关库了没

**Comment by SamSongShan** [comment]
全了的  不然debug包不可能OK吧

**Comment by FlyJingFish** [comment]
```gradle
implementation 'io.github.FlyJingFish.AndroidAop:android-aop-core:1.9.3'
implementation 'io.github.FlyJingFish.AndroidAop:android-aop-annotation:1.9.3'
```

你确定这两个你都弄了？

**Comment by SamSongShan** [comment]
我引用的是本地的  
api project(path: ':library-aop-annotation')
ksp project(':library-aop-ksp')
api project(path: ':library-aop-core')


会不会和我用了kapt 有关

**Comment by FlyJingFish** [comment]
最起码你先按文档配置跑起来没问题了。你再这么搞。你把代码弄成本地的，谁知道你少弄了什么。
