### ISSUE TITLE
接入后运行失败 提示 ; is missing

### ISSUE THREAD

**Issue by CPT-CJS** [FlyJingFish/AndroidAOP#25]
### 描述一下大概怎么回事
接入后运行失败 提示 ; is missing

### 你的代码
根目录的gradle：
buildscript {

    ext.kotlin_version = '1.8.0'
    ext.therouter_versioin = '1.2.2'
    ext.room_version = "2.4.3"

    apply from: 'config.gradle'
    apply from: 'VAConfig.gradle'

    repositories {
        google()
        mavenCentral()
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://maven.google.com' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url 'https://www.jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url "https://s01.oss.sonatype.org/content/groups/public" }
        maven { url = uri("https://storage.googleapis.com/r8-releases/raw") }
        jcenter()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath "cn.therouter:plugin:$therouter_versioin"
        classpath 'com.google.gms:google-services:4.3.15'
//        classpath 'com.google.gms:google-services:4.4.1'
        classpath("com.android.tools:r8:8.3.37")
        classpath 'io.github.FlyJingFish.AndroidAop:android-aop-plugin:2.0.5'
    }

}

plugins {
    id 'com.google.devtools.ksp' version '1.8.0-1.0.9' apply false
//    id "io.github.FlyJingFish.AndroidAop.android-aop" version "1.7.2" apply true
}
apply plugin: "android.aop"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com' }
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url 'https://www.jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url "https://s01.oss.sonatype.org/content/groups/public" }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

appmodule的gradle：
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    //引入插件,找到项目里全部的app模块（一般只会有一个，特殊项目会有多个）。
    //也就是整个工程的所有build.gradle文件里面，只要是有com.android.application这个的模块，都要加上如下代码
    id "therouter"
    id 'com.google.gms.google-services'
    id 'com.google.devtools.ksp'
    id "io.github.FlyJingFish.AndroidAop.android-aop"
    id 'android.aop'
}
apply plugin: 'kotlin-kapt'

androidAopConfig {
    // enabled 为 false 切面不再起作用，默认不写为 true
    enabled true
    // include 不设置默认全部扫描，设置后只扫描设置的包名的代码
//    include '你项目的包名','自定义module的包名','自定义module的包名'
    // exclude 是扫描时排除的包
    // 可排除 kotlin 相关，提高速度
    exclude 'kotlin.jvm', 'kotlin.internal','kotlinx.coroutines.internal', 'kotlinx.coroutines.android'

    // verifyLeafExtends 是否开启验证叶子继承，默认打开，@AndroidAopMatchClassMethod 和 @AndroidAopCollectMethod 如果没有设置 LEAF_EXTENDS，可以关闭
    verifyLeafExtends true
    //默认关闭，开启在 Build 或 打包后 将会生成切点信息json文件在 app/build/tmp/cutInfo.json
    cutInfoJson false
    //默认开启，设置 false 后会没有增量编译效果 筛选（关键字： AndroidAOP woven info code） build 输出日志可看时间
    increment true//修改、增加、删除匹配、收集切面的话，就会走全量编译
}

dependencies {
 testImplementation(this.rootProject.ext.dependencies.junit)
    androidTestImplementation(this.rootProject.ext.dependencies.junitExt)
    androidTestImplementation(this.rootProject.ext.dependencies.junitEspressoCore)
    kapt this.rootProject.ext.dependencies.therouter_apt
    implementation project(':module-landscape-launcher')
    implementation project(path: ':module-apkUpdate')
    implementation project(path: ':module-umeng')

    implementation 'io.github.FlyJingFish.AndroidAop:android-aop-core:2.0.5'
    implementation 'io.github.FlyJingFish.AndroidAop:android-aop-annotation:2.0.5'
    //非必须项 👇，如果你想自定义切面需要用到，⚠️支持Java和Kotlin代码写的切面
    ksp 'io.github.FlyJingFish.AndroidAop:android-aop-ksp:2.0.5'
}

### 错误日志
> Task :app:debugAssembleAndroidAopTask
AndroidAOP woven info code start
Merge jar error entry:[com/google/android/gms/dynamic/zae.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/cmic/sso/sdk/view/h$2.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/cmic/sso/sdk/view/h$1.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/cmic/sso/sdk/view/LoginAuthActivity.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$6.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$5.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$7.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$8.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$11.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/LoginAuthActivity$10.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/PrivacyDialogActivity$3.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/PrivacyDialogActivity$7.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/PrivacyDialogActivity$1.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/PrivacyDialogActivity$4.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/PrivacyDialogActivity$2.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����
Merge jar error entry:[com/mobile/auth/gatewayauth/activity/AuthWebVeiwActivity$1.class], error message:java.lang.ArrayIndexOutOfBoundsException,ͨ�����������Ҫ������Android Studio,Ȼ��cleanһ����Ŀ���ɣ�������������뵽Github��ϵ����

> Task :app:debugAssembleAndroidAopTask FAILED

Execution failed for task ':app:debugAssembleAndroidAopTask'.
> javassist.CannotCompileException: [source error] ; is missing

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:debugAssembleAndroidAopTask'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: java.lang.RuntimeException: javassist.CannotCompileException: [source error] ; is missing
	at com.flyjingfish.android_aop_plugin.utils.ClassFileUtils.wovenInfoInvokeClass(ClassFileUtils.kt:64)
	at com.flyjingfish.android_aop_plugin.tasks.AssembleAndroidAopTask.wovenIntoCode(AssembleAndroidAopTask.kt:633)
	at com.flyjingfish.android_aop_plugin.tasks.AssembleAndroidAopTask.scanFile(AssembleAndroidAopTask.kt:85)
	at com.flyjingfish.android_aop_plugin.tasks.AssembleAndroidAopTask.taskAction(AssembleAndroidAopTask.kt:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:236)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:221)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:204)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:187)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:165)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:124)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:80)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:58)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:181)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:71)
	at org.gradle.internal.Either$Right.fold(Either.java:175)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:69)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:102)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:254)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:91)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:56)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:281)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:139)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: javassist.CannotCompileException: [source error] ; is missing
	at javassist.CtBehavior.setBody(CtBehavior.java:474)
	at javassist.CtBehavior.setBody(CtBehavior.java:440)
	at com.flyjingfish.android_aop_plugin.utils.ClassFileUtils.wovenInfoInvokeClass(ClassFileUtils.kt:60)
	... 119 more
Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:611)
	at javassist.compiler.Parser.parseStatement(Parser.java:295)
	at javassist.compiler.Parser.parseBlock(Parser.java:307)
	at javassist.compiler.Parser.parseStatement(Parser.java:261)
	at javassist.compiler.Javac.compileBody(Javac.java:219)
	at javassist.CtBehavior.setBody(CtBehavior.java:466)
	... 121 more

### 库的版本号:
io.github.FlyJingFish.AndroidAop:android-aop-plugin:2.0.5

**Comment by FlyJingFish** [comment]
把你所有的切点函数发一下

**Comment by CPT-CJS** [comment]
如下：
@AndroidAopMatchClassMethod(
    targetClassName = "android.view.View.OnClickListener",
    methodName = ["onClick"],
    type = MatchType.EXTENDS //type 一定是 EXTENDS 因为你想 hook 所有继承了 OnClickListener 的类
)
class MatchOnClick : MatchClassMethod {
    //    @SingleClick(5000) //联合 @SingleClick ，给所有点击增加防多点，6不6
    override fun invoke(joinPoint: ProceedJoinPoint, methodName: String): Any? {
        Log.e("MatchOnClick", "=====invoke=====$methodName")
        return joinPoint.proceed()
    }
}

**Comment by FlyJingFish** [comment]
> 如下： @AndroidAopMatchClassMethod( targetClassName = "android.view.View.OnClickListener", methodName = ["onClick"], type = MatchType.EXTENDS //type 一定是 EXTENDS 因为你想 hook 所有继承了 OnClickListener 的类 ) class MatchOnClick : MatchClassMethod { // @singleclick(5000) //联合 @singleclick ，给所有点击增加防多点，6不6 override fun invoke(joinPoint: ProceedJoinPoint, methodName: String): Any? { Log.e("MatchOnClick", "=====invoke=====$methodName") return joinPoint.proceed() } }

只有这一个？

**Comment by CPT-CJS** [comment]
对，我刚接入。就想弄个view点击事件监听。没加其他东西了

**Comment by FlyJingFish** [comment]
你加一下首页那个群

**Comment by FlyJingFish** [comment]
新版本已尝试修复此问题

如果还有问题可加群详细聊，或者你使用 include 缩小范围或可解决
