### ISSUE TITLE
出现递归调用

### ISSUE THREAD

**Issue by zhangxqBeta** [FlyJingFish/AndroidAOP#41]
### AndroidAopReplaceClass 和 AndroidAopReplaceMethod 配合使用的时候直接调用，出现了递归调用
按照文档方式接入，按道理应该规避了递归
![image](https://github.com/user-attachments/assets/40744ea9-b0e4-43fd-93fe-22f46e59c22e)

### 代码如下：
```
package com.lit.app.aspect

import android.text.SpannableStringBuilder
import com.flyjingfish.android_aop_annotation.anno.AndroidAopReplaceClass
import com.flyjingfish.android_aop_annotation.anno.AndroidAopReplaceMethod

@AndroidAopReplaceClass("android.text.SpannableStringBuilder")
object AOPReplaceSpannableStringBuilder {
    @JvmStatic
    @AndroidAopReplaceMethod("void setSpan(java.lang.Object,int,int,int)")
    fun setSpan(thisObj: SpannableStringBuilder, what: Any, start: Int, end: Int, flags: Int) {
        log("replace android.text.SpannableStringBuilder.setSpan")
        thisObj.setSpan(what, start, end, flags)
    }
}
```

###配置
```
// 插桩工具配置
androidAopConfig {
    // 项目地址：https://github.com/FlyJingFish/AndroidAOP
    // 是否开启AOP
    enabled true
    // debug 为true打开日志方便调试
    debug false
    // 默认关闭，开启后将会生成切点信息json文件在 /build/tmp/cutInfo.json
    cutInfoJson true
    // verifyLeafExtends 是否开启验证叶子继承，默认打开，@AndroidAopMatchClassMethod 和 @AndroidAopCollectMethod 如果没有设置 LEAF_EXTENDS，可以关闭
    verifyLeafExtends false
    // 默认开启，设置 false 后会没有增量编译效果，修改、增加、删除匹配、收集切面的话，就会走全量编译
    increment false
}
```

### 错误日志
```
Caused by: java.lang.StackOverflowError: stack size 8192KB
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.isWatcher(SpannableBuilder.java:108)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:135)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                     	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
                                                                                                    	at com.lit.app.aspect.AOPReplaceSpannableStringBuilder.setSpan(AOPReplaceSpannableStringBuilder.kt:13)
                                                                                                    	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
```

**Comment by FlyJingFish** [comment]
我的说明是直接调用没问题，这个报错堆栈明显不是发生在切面内部，而是在其他位置`androidx.emoji2.text.SpannableBuilder.setSpan` ，看样子符合我说的间接调用的情况，你的配置并没有规避这一情况

**Comment by zhangxqBeta** [comment]
解决方案是在配置中增加exclude配置吗？
exclude 'androidx.emoji2.text.SpannableBuilder'

**Comment by FlyJingFish** [comment]
不知是不是出问题前你写了间接调用的代码，然后你发现之后又修改了切面的代码改为直接调用，改完之后又没有clean。

如果是这一情况的话，只需要在你提供代码的基础上clean一下就好了。

如果你仍旧想间接调用回原方法，则必须将中间的包含替换代码的类全部排除掉

**Comment by FlyJingFish** [comment]
不管如何每次修改切面代码都要进行clean

**Comment by zhangxqBeta** [comment]
我发现这个插桩很多地方都生效了，没问题，只有这里递归起来了
![image](https://github.com/user-attachments/assets/08db1371-15fe-485d-af94-346cf010f3c2)
可能是因为这里比较特殊，它是super方式调用的
如果我把这里排除掉，这里的插桩就失效了

另外，我发现修改玩切面后，有的时候不止要clean，还必须得重启android studio才能生效

**Comment by FlyJingFish** [comment]
要学会变通嘛，你传进来第一个参数可以拿到class对象，可以做针对性的处理，如果是这个类你在切面处理那里也调用super的方法就好了

**Comment by FlyJingFish** [comment]
如果对象的class对象属于你设置子类，就换成对象的super的调用

**Comment by FlyJingFish** [comment]
你说的clean问题，我电脑一直没问题，另外你发现的这一问题，我将在下一版本中解决掉，当下你只能按我说的做处理了

**Comment by zhangxqBeta** [comment]
好的，等你的包吧，我这边不着急，感谢解答

**Comment by zhangxqBeta** [comment]
新包已经ok了，大佬神速

**Comment by FlyJingFish** [comment]
千言万语不如一个star
