### ISSUE TITLE
IOException 被 转换成了RuntimeException，导致网络异常不能被正确处理

### ISSUE THREAD

**Issue by zhangxqBeta** [FlyJingFish/AndroidAOP#43]
### 你的代码
```
@AndroidAopMatchClassMethod(
    targetClassName = "okhttp3.internal.http.BridgeInterceptor",
    methodName = ["intercept"],
    type = MatchType.SELF
)
class BridgeInterceptorIntercept: MatchClassMethod {
    @Throws(IOException::class)
    override fun invoke(joinPoint: ProceedJoinPoint, methodName: String): Response {
        log("okhttp3.internal.http.BridgeInterceptor.$methodName")
        return joinPoint.proceed() as Response
    }
}
```

![image](https://github.com/user-attachments/assets/720bf50d-7a97-4c42-aa89-3863ee873a1c)

### 错误日志
```
          Fatal Exception: java.lang.RuntimeException: java.net.SocketException: Socket closed
       at com.flyjingfish.android_aop_annotation.utils.Utils.getRealRuntimeException(Utils.kt:121)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.realProceed(ProceedJoinPointImpl.java:175)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.proceed(ProceedJoinPointImpl.java:95)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.proceed(ProceedJoinPointImpl.java:83)
       at com.lit.app.aspect.BridgeInterceptorIntercept.invoke(AOPHook.kt:75)
       at com.lit.app.aspect.BridgeInterceptorIntercept.invoke(AOPHook.kt:54)
       at com.flyjingfish.android_aop_annotation.AndroidAopJoinPoint.joinPointExecute(AndroidAopJoinPoint.java:286)
       at okhttp3.internal.http.BridgeInterceptor.intercept(:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.lit.app.monitor.OkHttpLibraryGlideModule$1.intercept(OkHttpLibraryGlideModule.java:101)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
```
 Caused by java.net.SocketException: Socket closed
       at java.net.SocketInputStream.read(SocketInputStream.java:188)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
       at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
       at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
       at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.realProceed(ProceedJoinPointImpl.java:165)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.proceed(ProceedJoinPointImpl.java:95)
       at com.flyjingfish.android_aop_annotation.impl.ProceedJoinPointImpl.proceed(ProceedJoinPointImpl.java:83)
       at com.lit.app.aspect.BridgeInterceptorIntercept.invoke(AOPHook.kt:75)
       at com.lit.app.aspect.BridgeInterceptorIntercept.invoke(AOPHook.kt:54)
       at okhttp3.internal.http.BridgeInterceptor.intercept(:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.lit.app.monitor.OkHttpLibraryGlideModule$1.intercept(OkHttpLibraryGlideModule.java:101)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
        
```

### 库的版本号:
2.2.8

![image](https://github.com/user-attachments/assets/f61da9c9-ecde-4b4f-a188-c4481d3e990f)

**Comment by zhangxqBeta** [comment]
sorry，代码截图贴重复了

**Comment by FlyJingFish** [comment]
你想怎么改

**Comment by zhangxqBeta** [comment]
我觉得你可以处理自己定义的异常，其他的异常就正常抛出去，那些异常不是当前库引入的，由外面自己处理比较好

**Comment by FlyJingFish** [comment]
嗯。目前所做的处理是为了去除报错堆栈杂质信息，只是重新抛出时针对非运行时异常包装了一下，并不是没有抛出。
嗯……我删一下包装，由于最近mavenCentral抽风了，是无法发包的，等恢复正常时再发，敬请关注！
