### ISSUE TITLE
示例运行出错

### ISSUE THREAD

**Issue by hiquanta** [FlyJingFish/AndroidAOP#7]
### 描述一下大概怎么回事
运行示例

### 你的代码
运行SecondActivity Scheduled时出错 

### 错误日志
FATAL EXCEPTION: main
                                                                                                    Process: com.flyjingfish.androidaop, PID: 11763
                                                                                                    java.lang.RuntimeException: java.lang.NoSuchMethodException: lambda$onCreate$1 [class android.view.View]
                                                                                                    	at com.flyjingfish.android_aop_annotation.AndroidAopJoinPoint.setArgs(AndroidAopJoinPoint.java:179)
                                                                                                    	at com.flyjingfish.androidaop.SecondActivity.lambda$onCreate$1$com-flyjingfish-androidaop-SecondActivity(Unknown Source:31)
                                                                                                    	at com.flyjingfish.androidaop.SecondActivity$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:6294)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
                                                                                                    	at android.view.View$PerformClick.run(View.java:24774)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6518)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                                    Caused by: java.lang.NoSuchMethodException: lambda$onCreate$1 [class android.view.View]
                                                                                                    	at java.lang.Class.getMethod(Class.java:2068)
                                                                                                    	at java.lang.Class.getDeclaredMethod(Class.java:2047)
                                                                                                    	at com.flyjingfish.android_aop_annotation.AndroidAopJoinPoint.setArgs(AndroidAopJoinPoint.java:173)
                                                                                                    	at com.flyjingfish.androidaop.SecondActivity.lambda$onCreate$1$com-flyjingfish-androidaop-SecondActivity(Unknown Source:31) 
                                                                                                    	at com.flyjingfish.androidaop.SecondActivity$$ExternalSyntheticLambda1.onClick(Unknown Source:2) 
                                                                                                    	at android.view.View.performClick(View.java:6294) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:24774) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6518) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

### 库的版本号:
最新的

**Comment by hiquanta** [comment]
补充：  测试发现是v -> code 这种lambda表达式导致的，这是什么原因呢？

**Comment by FlyJingFish** [comment]
之前一直没注意过SecondActivity有这个bug，我猜测可能是打包时lambda的表达式生成的函数被重命名了，目前原因尚不清楚呀

**Comment by FlyJingFish** [comment]
[最新版本已修复此bug](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.1)，稍后可以尝试获取最新版本
